# Check if the latest version of the external libs are working with the current code 

name: Dependency check

on:
  schedule:
    - cron:  '0 1 * * *'
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # remove the fixed version to allow installing the latest
        cat requirements.txt | grep -v '^\-e' | cut -d = -f 1 | xargs -n1 pip install -U
        # remove the requirement of requirements.txt
        tail -n +2 requirements-dev.txt | xargs -n1 pip install
    - name: Test with pytest
      run: |
        pytest
