name: Pypi

on:
  release:
    types: [ published ]

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Create Distribution Folder
      run: python setup.py sdist

    - name: Publish to Pypi
      env:
        USERNAME: ${{ secrets.PYPI_USERNAME }}
        PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python -m pip install --upgrade pip
        pip install twine==3.2.0
        twine upload --username $USERNAME --password $PASSWORD dist/*
